### ISSUE TITLE
autolibs option does not support 3, 4

### ISSUE THREAD

**Issue by billywatson** [wayneeseguin/rvm-capistrano#107]
Mode 3 (packages) and 4 (enable) are not supported by this gem. https://rvm.io/rvm/autolibs

**Comment by mpapis** [comment]
more details please

**Comment by billywatson** [comment]
got the pull request submitted that fixes this, I believe. I didn't actually check if there were tests

**Comment by billywatson** [comment]
It looks like there are tests, but nothing specific for autolibs

**Comment by mpapis** [comment]
closing in favor of #108
