### ISSUE TITLE
RVM always re-installed; avoid if current?

### ISSUE THREAD

**Issue by jdashton** [wayneeseguin/rvm-capistrano#111]
When capistrano runs the rvm:install_ruby task it refuses to re-install ruby if the requested version is already present. However, with the rvm:install_rvm task it blindly re-installs rvm, even though the installed version is the same as the version being downloaded. Is this something that I have configured incorrectly? Or can we get capistrano to check for a current rvm before re-installing the same version on top of itself? I normally wouldn't care, but it takes several seconds to complete the install, and I'd rather not have to wait.

**Comment by mpapis** [comment]
unfortunately this is shortcoming of RVM itself, but as a bonus you get all the autofixes from RVM installer.
